#Configuración de Alertas MotoCore
#Sun Apr 27 22:09:03 COT 2025
appointment.alert.new=true
appointment.alert.reminder=true
appointment.alert.status=true
appointment.alerts.enabled=true
appointment.reminder.days=2
notification.email=
notification.frequency=hour
notification.method=system
stock.alert.type=exact
stock.alerts.enabled=true
stock.threshold=5
